# Generated by Django 5.2.11 on 2026-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('REGISTRAR', 'Registrar'), ('MIS', 'Management Information Systems'), ('KIOSK', 'Kiosk (API Only)')], default='REGISTRAR', max_length=20),
        ),
    ]
