# Generated by Django 5.2.11 on 2026-04-09 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dashboard', 'Dashboard & Analytics'), ('tickets', 'Ticket Management'), ('queues', 'Queue Management'), ('users', 'User Management'), ('system', 'System Configuration'), ('audit', 'Audit & Security'), ('exports', 'Data Export & Import'), ('custom', 'Custom Permission')], default='custom', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_builtin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Custom Permission',
                'verbose_name_plural': 'Custom Permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('REGISTRAR', 'Registrar'), ('MIS', 'Management Information Systems'), ('KIOSK', 'Kiosk (API Only)'), ('CUSTOM', 'Custom Role')], default='REGISTRAR', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.custompermission')),
            ],
            options={
                'verbose_name': 'Custom Role',
                'verbose_name_plural': 'Custom Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.customrole'),
        ),
    ]
