# Generated by Django 5.2.11 on 2026-04-09 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_custompermission_alter_user_role_customrole_and_more'),
        ('queues', '0004_remove_servicetype_assigned_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text="User's assigned role which determines permissions", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.customrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text="User's primary department for department-level permission filtering", null=True, on_delete=django.db.models.deletion.SET_NULL, to='queues.department'),
        ),
    ]
