# Generated by Django 5.2.11 on 2026-05-06 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_role_alter_user_custom_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique API key for authentication', max_length=40, unique=True)),
                ('name', models.CharField(help_text="Name/description of this API key (e.g., 'Kiosk Device 1')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Disable key without deleting it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful authentication', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this API key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
