# Generated by Django 5.2.11 on 2026-03-28 06:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('max_entries_per_day', models.PositiveIntegerField(default=0, help_text='Maximum tickets per day (0 = unlimited)')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('assigned_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('REGISTRAR', 'REGISTRAR'), ('MIS', 'MIS')], default='MIS', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queues.department')),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(max_length=10)),
                ('qr_code_data', models.TextField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('SERVED', 'Served'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('section', models.CharField(max_length=100)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queues.department')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.servicetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('queue_number', 'service_type', 'created_at'), name='unique_queue_per_service_per_day')],
            },
        ),
    ]
