# Generated by Django 5.2.11 on 2026-04-09 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='assigned_role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('REGISTRAR', 'Registrar'), ('MIS', 'Management Information Systems'), ('KIOSK', 'Kiosk (API Only)')], default='MIS', max_length=20),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ticket_type', models.CharField(choices=[('SERVICE', 'Service Request'), ('COMPLAINT', 'Customer Complaint'), ('INQUIRY', 'General Inquiry'), ('FEEDBACK', 'Feedback/Survey'), ('OTHER', 'Other')], default='SERVICE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed/Served'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned to Queue')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_id', models.CharField(blank=True, help_text='ID or Account number', max_length=50)),
                ('qr_code', models.TextField(help_text='UUID-based unique identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('wait_time_minutes', models.IntegerField(blank=True, null=True)),
                ('resolution_time_minutes', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.department')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.servicetype')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department', 'created_at'], name='queues_tick_departm_71b607_idx'), models.Index(fields=['status', 'created_at'], name='queues_tick_status_2b4076_idx'), models.Index(fields=['assigned_to', 'status'], name='queues_tick_assigne_40d014_idx')],
            },
        ),
    ]
