# Generated by Django 5.2.11 on 2026-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_alter_servicetype_assigned_role_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='assigned_role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('REGISTRAR', 'Registrar'), ('MIS', 'Management Information Systems'), ('KIOSK', 'Kiosk (API Only)'), ('CUSTOM', 'Custom Role')], default='MIS', max_length=20),
        ),
    ]
