# Generated by Django 5.2.11 on 2026-04-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_alter_servicetype_assigned_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='assigned_role',
        ),
    ]
