# Generated by Django 5.2.11 on 2026-05-03 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_remove_servicetype_assigned_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['created_at', 'status'], name='idx_created_status'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['department', 'status'], name='idx_dept_status'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['service_type', 'created_at'], name='idx_service_created'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['department', 'created_at', 'status'], name='idx_dept_created_status'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['created_date'], name='idx_created_date'),
        ),
    ]
