# Generated by Django 5.2.11 on 2026-04-09 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_UPDATED', 'Ticket Updated'), ('TICKET_COMPLETED', 'Ticket Completed'), ('TICKET_CANCELLED', 'Ticket Cancelled'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_RETURNED', 'Ticket Returned'), ('QUEUE_ENTRY_CREATED', 'Queue Entry Created'), ('QUEUE_ENTRY_UPDATED', 'Queue Entry Updated'), ('QUEUE_ENTRY_SERVED', 'Queue Entry Served'), ('DEPT_CREATED', 'Department Created'), ('DEPT_UPDATED', 'Department Updated'), ('SERVICE_CREATED', 'Service Type Created'), ('SERVICE_UPDATED', 'Service Type Updated'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('ROLE_CHANGED', 'User Role Changed'), ('UNAUTHORIZED', 'Unauthorized Access Attempt'), ('API_KEY_USED', 'Kiosk API Key Used'), ('PERMISSION_DENIED', 'Permission Denied'), ('SETTINGS_CHANGED', 'Settings Changed'), ('EXPORT_CREATED', 'Data Export Created')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('object_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.IntegerField()),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'action'], name='audit_audit_timesta_0aa31e_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
